language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run web bin/rails db:setup RAILS_ENV=test && docker-compose run web rspec
