version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
  web:
    build: .
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:5432@db
    depends_on:
      - db
